version: '3.4'

services:
  portal-de-compras-prod:
    image: test:hmg
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - portal
    ports:
      - "1550:3000"
networks:
  portal:
    name: portal
    external: true
